[versions]
lombok = "1.18.44"
junit = "6.0.3"
slf4j = "2.0.17"
logback = "1.5.32"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
