[versions]
lombok = "1.18.44"
junit = "6.0.3"
slf4j = "2.0.17"
logback = "1.5.32"
agrona = "2.4.1"
disruptor = "3.4.2"
jmh = "1.37"
guava = "33.0.0-jre"
hdrhistogram = "2.2.2"

[libraries]
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
agrona = { module = "org.agrona:agrona", version.ref = "agrona" }
disruptor = { module = "com.lmax:disruptor", version.ref = "disruptor" }
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hdrhistogram = { module = "org.hdrhistogram:HdrHistogram", version.ref = "hdrhistogram" }
